services:
  dashboard:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: dashboard
    ports:
      - "49513:3000"
    #restart: always
    tty: true
    volumes:
      - /app/node_modules
      - type: bind
        source: ./
        target: /app